/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.knapsackdemp;

import java.awt.Dimension;
import java.io.File;
import java.net.URL;

import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author i329810
 */
public class NewKnapSackDemo extends javax.swing.JFrame {

    
    public int currentWeight = 0;
    public int currentValue = 0; 
    
    public JPanel weightPanels[]; 
    public JPanel emptyPanel;
    public int[] colorX = {255,255,124,100,65,147,216,218,255,244};
    public int colorY[] = {0,255,252,149,105,112,191,112,105,164};
    public int colorZ[] = {0,0,0,237,225,219,216,214,180,96};
    public int emptyPanelLength = 400;
    

    public int maxWeight = 20;

    public int[] weights;
    public int[] values; 

    public int[] heights;

    
    /**
     * Creates new form KnapSackDemo
     */
    public NewKnapSackDemo() {

        GenerateKnapSack problem =  new GenerateKnapSack(406,1);
        System.out.println("Max wieght : "+ problem.getMaxWeight());
        System.out.println("Generated Weights");
        for(int weight : problem.getWeights()) {
            System.out.println(weight);
        }

        System.out.println("Generated Values"); 
        for(int value: problem.getValues()) {
            System.out.println(value);
        }

        this.maxWeight = problem.getMaxWeight();
        this.weights = problem.getWeights();
        this.values = problem.getValues();
        this.heights = problem.getHeights();


        //System.out.println(getClass().getResource("deseimage.png"));
        initComponents();
        baseInitializeBucket();
        
        
    }


    public void setCurrentValuesText() {
        this.maxWeightLabel.setText("Maximum Weight: " + this.maxWeight);
        this.currentWeightLabel.setText("Current Weight: " + this.currentWeight);
        this.currentValueLabel.setText("Current Value: "+ this.currentValue);
    }

    public void generateProblem() {
        GenerateKnapSack problem =  new GenerateKnapSack(406,1);
        System.out.println("Max wieght : "+ problem.getMaxWeight());
        System.out.println("Generated Weights");
        for(int weight : problem.getWeights()) {
            System.out.println(weight);
        }

        System.out.println("Generated Values"); 
        for(int value: problem.getValues()) {
            System.out.println(value);
        }

        this.maxWeight = problem.getMaxWeight();
        this.weights = problem.getWeights();
        this.values = problem.getValues();
        this.heights = problem.getHeights();
        baseInitializeBucket();
        setButtonLabels();
        setCurrentValuesText();
    }
    public void cleanup() {
        emptyPanelLength = 400;
        this.currentValue = 0;
        this.currentWeight = 0;
        closeAllWeightPanels();
        setCurrentValuesText();
    }
    public void newProblem() {
        cleanup();
        generateProblem();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        weightButton1 = new javax.swing.JButton();
        weightButton2 = new javax.swing.JButton();
        weightButton3 = new javax.swing.JButton();
        weightButton4 = new javax.swing.JButton();
        weightButton5 = new javax.swing.JButton();
        weightButton6 = new javax.swing.JButton();
        weightButton7 = new javax.swing.JButton();
        weightButton8 = new javax.swing.JButton();
        weightButton9 = new javax.swing.JButton();
        weightButton10 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        newProblemButton = new javax.swing.JButton();
        solveButton = new javax.swing.JButton();
        currentWeightLabel = new javax.swing.JLabel();
        currentValueLabel = new javax.swing.JLabel();
        maxWeightLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new JLabel();//new JLabel(new ImageIcon(getClass().getClassLoader().getResource("resources/deseimage.png")));
        jLabel2 = new JLabel();//new JLabel(new ImageIcon(getClass().getClassLoader().getResource("resources/iisclogo.png")));
        jLabel3 = new javax.swing.JLabel();
        initPanels();

        solveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanup();
                solveKnapSack();
            }
          
        });

        newProblemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanup();
                generateProblem();
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setButtonLabels();
        setButtonSizes();
        weightButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightButtonActionPerformed(0);
            }
        });
        weightButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightButtonActionPerformed(1);
            }
        });
        weightButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightButtonActionPerformed(2);
            }
        });
        weightButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightButtonActionPerformed(3);
            }
        });
        weightButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightButtonActionPerformed(4);
            }
        });
        weightButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightButtonActionPerformed(5);
            }
        });
        weightButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightButtonActionPerformed(6);
            }
        });
        weightButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightButtonActionPerformed(7);
            }
        });
        weightButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightButtonActionPerformed(8);
            }
        });
        weightButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightButtonActionPerformed(9);
            }
        });


        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(weightButton1)
                    .addComponent(weightButton2)
                    .addComponent(weightButton3)
                    .addComponent(weightButton4)
                    .addComponent(weightButton5))
                .addGap(79, 79, 79)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weightButton6)
                    .addComponent(weightButton10)
                    .addComponent(weightButton9)
                    .addComponent(weightButton8)
                    .addComponent(weightButton7))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        //jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {weightButton1, weightButton10, weightButton2, weightButton3, weightButton4, weightButton5, weightButton6, weightButton7, weightButton8, weightButton9});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightButton1)
                    .addComponent(weightButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightButton2)
                    .addComponent(weightButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightButton3)
                    .addComponent(weightButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightButton4)
                    .addComponent(weightButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightButton5)
                    .addComponent(weightButton10))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        newProblemButton.setText("New Problem");

        solveButton.setText("Solve");
        maxWeightLabel.setText("Maximum Weight: ");
        currentWeightLabel.setText("Current Weight: ");

        currentValueLabel.setText("Current Value:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxWeightLabel)
                    .addComponent(currentWeightLabel)
                    .addComponent(currentValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                .addComponent(newProblemButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(solveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newProblemButton)
                            .addComponent(solveButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(maxWeightLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(currentWeightLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(currentValueLabel))))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jPanel6.setAlignmentX(0.0F);
        jPanel6.setPreferredSize(new java.awt.Dimension(130, 406));
        jPanel6.setPreferredSize(new java.awt.Dimension(120,406));
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 0, 36)); // NOI18N
        jLabel3.setText("Help Harry Potter");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void solveKnapSack() {

        SolveKnapSack sol = new SolveKnapSack(this.maxWeight, this.weights, this.values, 10);

        int counter = 0;
        for(int wght : sol.getSolvedWeights()) {

            if(wght == -1) {
                if(counter == 0 ) {
                    System.out.println("No Solution");
                }
                break;
            }
            counter++;

            for(int i =0; i<10; i++) {
                if(this.weights[i] == wght) {
                    weightButtonActionPerformed(i);
                    break;
                }
            }
        }

    }

    public void setButtonSizes() {
        int width =200; 
        int length = 40; 
        Dimension d = new Dimension(width,length);
        weightButton1.setSize(width,length);
        weightButton1.setPreferredSize(d);
        weightButton1.setMaximumSize(d);
        

        weightButton2.setSize(width,length);
        weightButton2.setPreferredSize(d);
        weightButton2.setMaximumSize(d);

        weightButton3.setSize(width,length);
        weightButton3.setPreferredSize(d);
        weightButton3.setMaximumSize(d);

        weightButton4.setSize(width,length);
        weightButton4.setPreferredSize(d);
        weightButton4.setMaximumSize(d);

        weightButton5.setSize(width,length);
        weightButton5.setPreferredSize(d);
        weightButton5.setMaximumSize(d);

        weightButton6.setSize(width,length);
        weightButton6.setPreferredSize(d);
        weightButton6.setMaximumSize(d);

        weightButton7.setSize(width,length);
        weightButton7.setPreferredSize(d);
        weightButton7.setMaximumSize(d);

        weightButton8.setSize(width,length);
        weightButton8.setPreferredSize(d);
        weightButton8.setMaximumSize(d);

        weightButton9.setSize(width,length);
        weightButton9.setPreferredSize(d);
        weightButton9.setMaximumSize(d);

        weightButton10.setSize(width,length);
        weightButton10.setPreferredSize(d);
        weightButton10.setMaximumSize(d);

    }
    public void setButtonLabels() {
        weightButton1.setText("Weight: " + weights[0] + " Value : "+ values[0] );
        weightButton2.setText("Weight: " + weights[1] + " Value : "+ values[1] );
        weightButton3.setText("Weight: " + weights[2] + " Value : "+ values[2] );
        weightButton4.setText("Weight: " + weights[3] + " Value : "+ values[3] );
        weightButton5.setText("Weight: " + weights[4] + " Value : "+ values[4] );
        weightButton6.setText("Weight: " + weights[5] + " Value : "+ values[5] );
        weightButton7.setText("Weight: " + weights[6] + " Value : "+ values[6] );
        weightButton8.setText("Weight: " + weights[7] + " Value : "+ values[7] );
        weightButton9.setText("Weight: " + weights[8] + " Value : "+ values[8] );
        weightButton10.setText("Weight: " + weights[9] + " Value : "+ values[9] );



        weightButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(colorX[0], colorY[0], colorZ[0])));
        weightButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(colorX[1], colorY[1], colorZ[1])));
        weightButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(colorX[2], colorY[2], colorZ[2])));
        weightButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(colorX[3], colorY[3], colorZ[3])));
        weightButton5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(colorX[4], colorY[4], colorZ[4])));
        weightButton6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(colorX[5], colorY[5], colorZ[5])));
        weightButton7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(colorX[6], colorY[6], colorZ[6])));
        weightButton8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(colorX[7], colorY[7], colorZ[7])));
        weightButton9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(colorX[8], colorY[8], colorZ[8])));
        weightButton10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(colorX[9], colorY[9], colorZ[9])));
    }

    
    private void weightButtonActionPerformed(int buttonNumer) {
        
        if(weightPanels[buttonNumer].isVisible()) {
            weightPanels[buttonNumer].setVisible(false);
            currentWeight= currentWeight- weights[buttonNumer]; 
            currentValue = currentValue -values[buttonNumer]; 
            setCurrentValuesText();
            emptyPanelLength = emptyPanelLength + heights[buttonNumer];
            emptyPanel.setSize(120,emptyPanelLength);
            emptyPanel.setMaximumSize(new Dimension(120,emptyPanelLength));

        }else {
                
            if(currentWeightCheck(currentWeight+ weights[buttonNumer])) {
                JOptionPane.showMessageDialog(this, "You can only add upto  " + (maxWeight - currentWeight) + " weight");
            } else {
            weightPanels[buttonNumer].setVisible(true);
            weightPanels[buttonNumer].setSize(120,heights[buttonNumer]);
            weightPanels[buttonNumer].setMaximumSize(new Dimension(120,heights[buttonNumer]));
            emptyPanelLength = emptyPanelLength - heights[buttonNumer];
            emptyPanel.setSize(120,emptyPanelLength);
            emptyPanel.setMaximumSize(new Dimension(120,emptyPanelLength));
            currentWeight= currentWeight+ weights[buttonNumer]; 
            currentValue = currentValue +values[buttonNumer]; 
            setCurrentValuesText();

                
            }
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KnapSackDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KnapSackDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KnapSackDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KnapSackDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KnapSackDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentValueLabel;
    private javax.swing.JLabel currentWeightLabel;
    private javax.swing.JLabel maxWeightLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel  jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton newProblemButton;
    private javax.swing.JButton solveButton;
    private javax.swing.JButton weightButton1;
    private javax.swing.JButton weightButton10;
    private javax.swing.JButton weightButton2;
    private javax.swing.JButton weightButton3;
    private javax.swing.JButton weightButton4;
    private javax.swing.JButton weightButton5;
    private javax.swing.JButton weightButton6;
    private javax.swing.JButton weightButton7;
    private javax.swing.JButton weightButton8;
    private javax.swing.JButton weightButton9;
    // End of variables declaration//GEN-END:variables

    private void initPanels() {
        emptyPanel = new JPanel(); 
        emptyPanel.setVisible(true);
        emptyPanel.setSize(120,emptyPanelLength);
        emptyPanel.setMaximumSize(new Dimension(120,emptyPanelLength));
        jPanel6.add(emptyPanel);
        weightPanels = new JPanel[10];
        for(int i=0; i <10;i++) {
            weightPanels[i] = new javax.swing.JPanel();
            jPanel6.add(weightPanels[i]);
        }

    }

    private void baseInitializeBucket() {
    
        emptyPanel.setVisible(true);
        emptyPanel.setSize(120,emptyPanelLength);
        emptyPanel.setMaximumSize(new Dimension(120,emptyPanelLength));
        //jPanel6.add(emptyPanel);
        for(int i=0; i <10;i++) {
            weightPanels[i].setVisible(false);
            weightPanels[i].setBackground(new java.awt.Color(colorX[i], colorY[i], colorZ[i]));

        }
        
        
    }
    public void closeAllWeightPanels() {
        for(int i=0; i <10;i++) {
            weightPanels[i].setVisible(false);
        }
    }
    private boolean currentWeightCheck(int weight) {
        if(weight > maxWeight) {
            return true;
        }else {
            return false;
        }
    }

    private File getFileFromResources(String fileName) {

        ClassLoader classLoader = getClass().getClassLoader();

        URL resource = classLoader.getResource(fileName);
        if (resource == null) {
            throw new IllegalArgumentException("file is not found!");
        } else {
            return new File(resource.getFile());
        }

    }
}
